Repository AtlasRender/atlas-core, pull requests merged in 2020-10, with the labels that each got.

#1 Added basic server, controller.
  .gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/copyright/Pathfinder_copyright.xml
  .idea/copyright/profiles_settings.xml
  .idea/runConfigurations/Run_with_WS_tsc.xml
  .idea/runConfigurations/Run_with_nodemon.xml
  config.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/controllers/HelloWorld.ts
  src/controllers/Test.ts
  src/core/Controller.ts
  src/core/Server.ts
  src/entities/Customer.entity.ts
  src/entities/Job.entity.ts
  src/entities/User.entity.ts
  src/index.ts
  src/main.ts
  tsconfig.json
  yarn.lock
Labels: development

#2 [GLOBAL] Added app.yaml.
  app.yaml
  src/entities/Customer.entity.ts
Labels: development

#3 [GLOBAL] Edited package.json, tsconfig.json and app.yaml.
  app.yaml
  package.json
  tsconfig.json
Labels: development

#4 [GLOBAL] Edited Server.ts (fixed typo).
  src/core/Server.ts
Labels: development

#5 Basic set up docker and added Jest as testing library.
  .idea/jsLibraryMappings.xml
  .idea/pathfinder-core.iml
  Dockerfile
  babel.config.js
  docker-compose.yaml
  jest.config.js
  package.json
  src/controllers/Test.test.ts
  yarn.lock
Labels: dependencies, development, testing

#6 [GLOBAL] Added heroku Procfile.
  Procfile
  src/controllers/Test.ts
  src/core/Server.ts
Labels: development

#7 [GLOBAL] Added heroku PORT.
  src/index.ts
Labels: development

#8 [GLOBAL] Changed heroku Procfile.
  Procfile
Labels: development

#9 [GLOBAL] Changed launch scripts for heroku.
  package.json
  src/index.ts
Labels: development, enhancement

#10 [GLOBAL] Changed index file to use Server.ts.
  src/core/Server.ts
  src/index.ts
Labels: development

#11 [app.yaml] Deleted.
  app.yaml
Labels: bug

#19 [Database] Added typeorm Entities representing Database.
  .gitignore
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/dictionaries/Danil_Andreev.xml
  package.json
  src/config.json
  src/core/Server.ts
  src/entities/BasicPlugin.ts
  src/entities/Customer.entity.ts
  src/entities/GlobalPlugin.ts
  src/entities/Organization.ts
  src/entities/OrganizationLog.ts
  src/entities/Plugin.ts
  src/entities/RenderJob.ts
  src/entities/RenderJobLog.ts
  src/entities/RenderTask.ts
  src/entities/RenderTaskAttempt.ts
  src/entities/RenderTaskAttemptLog.ts
  src/entities/Role.ts
  src/entities/Slave.ts
  src/entities/User.entity.ts
  src/entities/User.ts
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: database, development

#35 Reworked some entities, added UsersController and OrganizationsController.
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dictionaries/Danil_Andreev.xml
  README.md
  docker-compose/pathfinder-core-start.yaml
  docker-compose/pathfinder-data-storage-start.yaml
  package.json
  src/controllers/HelloWorld.ts
  src/controllers/LoginController.ts
  src/controllers/OrganizationsController.ts
  src/controllers/Test.ts
  src/controllers/UsersController.ts
  src/core/Authenticator.ts
  src/core/Server.ts
  src/entities/BasicPlugin.ts
  src/entities/Organization.ts
  src/entities/OrganizationLog.ts
  src/entities/RenderJob.ts
  src/entities/RenderJobLog.ts
  src/entities/RenderTask.ts
  src/entities/RenderTaskAttempt.ts
  src/entities/RenderTaskAttemptLog.ts
  src/entities/Role.ts
  src/entities/Slave.ts
  src/entities/User.ts
  src/index.ts
  src/validators/UserRequestValidator.ts
  yarn.lock
Labels: development, entity

#36 Added Organization Controller.
  src/controllers/LoginController.ts
  src/controllers/OrganizationsController.ts
  src/controllers/UsersController.ts
  src/core/Server.ts
  src/entities/BasicPlugin.ts
  src/entities/GlobalPlugin.ts
  src/entities/Organization.ts
  src/entities/OrganizationLog.ts
  src/entities/RenderJob.ts
  src/entities/RenderJobLog.ts
  src/entities/RenderTask.ts
  src/entities/RenderTaskAttempt.ts
  src/entities/RenderTaskAttemptLog.ts
  src/entities/Role.ts
  src/entities/Slave.ts
  src/entities/User.ts
  src/interfaces/OutUser.ts
  src/validators/OrganizationRequestValidator.ts
  src/validators/UserRequestValidator.ts
Labels: development

#37 [Controllers] Some changes.
  src/controllers/LoginController.ts
  src/controllers/OrganizationsController.ts
  src/controllers/UsersController.ts
  src/validators/OrganizationRequestValidators.ts
  src/validators/UserRequestValidators.ts
Labels: development, testing

#38 Ajv support, CORS, Globals
  .idea/dataSources.xml
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239.xml
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239/storage_v2/_src_/database/postgres.edMnLQ.meta
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239/storage_v2/_src_/database/postgres.edMnLQ/schema/information_schema.FNRwLQ.meta
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239/storage_v2/_src_/database/postgres.edMnLQ/schema/pg_catalog.0S1ZNQ.meta
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239/storage_v2/_src_/database/postgres.edMnLQ/schema/public.abK9xQ.meta
  docker-compose/pathfinder-data-storage-start.yaml
  package.json
  src/config.json
  src/controllers/LoginController.ts
  src/controllers/OrganizationsController.ts
  src/controllers/UsersController.ts
  src/core/Authenticator.ts
  src/core/Server.ts
  src/entities/Role.ts
  src/entities/Slave.ts
  src/errors/RequestError.ts
  src/globals.ts
  src/index.ts
  src/utils/ajv-middleware/ajv-validation-middleware.ts
  src/validators/OrganizationRequestValidators.ts
  src/validators/UserRequestValidators.ts
  yarn.lock
Labels: database, dependencies, development

#39 Added git-crypt and other changes
  .gitattributes
  .github/workflows/docker-image-publish.yml
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/dictionaries/Danil_Andreev.xml
  .idea/jsLibraryMappings.xml
  .idea/pathfinder-core.iml
  config.json
  package.json
  src/config.json
  src/config.ts
  src/controllers/HelloWorld.ts
  src/controllers/LoginController.test.ts
  src/controllers/Test.test.ts
  src/controllers/Test.ts
  src/core/Server.ts
  src/index.ts
  src/interfaces/OutUser.ts
  src/interfaces/ServerConfig.ts
  src/interfaces/ServerOptions.ts
  yarn.lock
Labels: enhancement

#40 [docker-image-publish.yml] Fixed incorrect yaml.
  .github/workflows/docker-image-publish.yml
  .idea/git-crypt-project.xml
Labels: bug, invalid

#41 Changed data storage docker-compose config.
  .gitattributes
  docker-compose/pathfinder-data-storage-start.yaml
  src/config.ts
Labels: database, development

#48 Added RolesController, updated OrganizationController
  .idea/dataSources.xml
  .idea/jsLibraryMappings.xml
  src/config.json
  src/controllers/OrganizationsController.ts
  src/controllers/RolesController.ts
  src/entities/Organization.ts
  src/entities/Role.ts
  src/entities/User.ts
  src/errors/RequestError.ts
  src/index.ts
  src/validators/OrganizationRequestValidators.ts
Labels: development

#51 [RolesController] fixed constructor route mistake.
  src/controllers/RolesController.ts
Labels: development

#52 [CI] Added test route for testing GCloud.
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239.xml
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239/storage_v2/_src_/database/postgres.edMnLQ.meta
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239/storage_v2/_src_/database/postgres.edMnLQ/schema/information_schema.FNRwLQ.meta
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239/storage_v2/_src_/database/postgres.edMnLQ/schema/pg_catalog.0S1ZNQ.meta
  .idea/dataSources/5abb0c95-7d6c-47dd-a588-46e2f719d239/storage_v2/_src_/database/postgres.edMnLQ/schema/public.abK9xQ.meta
  src/controllers/RolesController.ts
Labels: testing

#58 Added RolesController and UserTokenController.
  .idea/dataSources.xml
  src/config.ts
  src/controllers/OrganizationsController.ts
  src/controllers/RolesController.ts
  src/controllers/UserTokensController.ts
  src/controllers/UsersController.ts
  src/core/Authenticator.ts
  src/entities/Organization.ts
  src/entities/Role.ts
  src/entities/User.ts
  src/entities/UserToken.ts
  src/index.ts
  src/interfaces/UserJwt.ts
  src/utils/ajv-middleware/ajv-validation-middleware.ts
  src/validators/OrganizationRequestValidators.ts
Labels: development

#59 [UserTokensController] Fixed bug with incorrect tokens selection.
  src/controllers/UserTokensController.ts
Labels: bug, controller, invalid

#62 Changed cors credentials policy to true
  src/controllers/UsersController.ts
  src/entities/BasicPlugin.ts
  src/entities/Organization.ts
  src/entities/OrganizationLog.ts
  src/entities/RenderJob.ts
  src/entities/RenderJobLog.ts
  src/entities/RenderTask.ts
  src/entities/RenderTaskAttempt.ts
  src/entities/RenderTaskAttemptLog.ts
  src/entities/Role.ts
  src/entities/Slave.ts
  src/entities/User.ts
  src/entities/UserToken.ts
  src/errors/RequestError.ts
  src/validators/UserRequestValidators.ts
Labels: development

#64 Finished user controller.
  .idea/inspectionProfiles/Project_Default.xml
  src/controllers/UsersController.ts
  src/validators/UserRequestValidators.ts
Labels: controller, development

#67 Changed AMQP lib
  .gitattributes
  .github/workflows/pathfinder-data-storage-update.yml
  .idea/pathfinder-core.iml
  docker-compose/pathfinder-data-storage-start-dev.yaml
  docker-compose/pathfinder-data-storage-start-prod.yaml
  docker-compose/pathfinder-data-storage-start.yaml
  package.json
  src/config.ts
  src/controllers/OrganizationsController.ts
  src/controllers/RolesController.ts
  src/core/Server.ts
  src/interfaces/ServerConfig.ts
  yarn.lock
Labels: dependencies, development

#70 Added edit for OrganizationController, RolesController
  .idea/inspectionProfiles/Project_Default.xml
  package.json
  src/controllers/LoginController.test.ts
  src/controllers/OrganizationsController.ts
  src/controllers/RolesController.ts
  src/index.ts
  src/validators/OrganizationRequestValidators.ts
  yarn.lock
Labels: development

#72 Edited POST/DELETE on /orgs/:org_id/users to add/remove multiple users.
  src/controllers/OrganizationsController.ts
  src/controllers/RolesController.ts
  src/validators/OrganizationRequestValidators.ts
Labels: controller, development

#75 [OrganizationsController] Fixed logic for adding/deleting users.
  src/controllers/OrganizationsController.ts
Labels: bug, controller

#78 Added GET /organizations/:organization_id/availableUsers - get users that are not in organization
  src/controllers/OrganizationsController.ts
  src/controllers/UsersController.ts
  src/validators/OrganizationRequestValidators.ts
  src/validators/UserRequestValidators.ts
Labels: controller, development

#79 GET /organizations/:organization_id/users now also returns user's roles.
  src/controllers/LoginController.test.ts
  src/controllers/OrganizationsController.ts
Labels: controller, development

#82 [RolesController] Fixed adding / deleting user to role.
  src/controllers/RolesController.ts
  src/validators/OrganizationRequestValidators.ts
  src/validators/UserRequestValidators.ts
Labels: bug, controller, development

#83 [RolesController] Fixed adding / deleting user to role. (again)
  src/controllers/RolesController.ts
Labels: bug, controller, development

#88 [RolesController] Fixed name checks on role edit.
  src/controllers/RolesController.ts
Labels: bug, development

#90 [Server] Added server.close() method.
  package.json
  src/controllers/LoginController.test.ts
  src/controllers/RolesController.ts
  src/core/Server.ts
  src/index.ts
Labels: bug, development

#91 Reworked Server to implement Singleton pattern
  package.json
  src/controllers/LoginController.test.ts
  src/core/Server.ts
  src/index.ts
  yarn.lock
Labels: bug, development, optimization

#94 (#84) organization user
  src/controllers/OrganizationsController.ts
Labels: development

#110 Created submit job controller
  .idea/dictionaries/Danil_Andreev.xml
  package.json
  src/controllers/JobController.ts
  src/core/JobEvent.ts
  src/core/Server.ts
  src/entities/RenderJob.ts
  src/entities/RenderTask.ts
  src/globals.ts
  src/index.ts
  src/interfaces/JobEventable.ts
  src/interfaces/RenderJobFields.ts
  src/interfaces/RenderTaskFields.ts
  src/processors/JobsProcessor.ts
  src/processors/TaskReportsProcessor.ts
  src/utils/getFramesFromRange.test.ts
  src/utils/getFramesFromRange.ts
  yarn.lock
Labels: controller, dependencies, development, entity

#111 [idea] Changed package manager.
  .idea/runConfigurations/Run_with_nodemon.xml
Labels: development, optimization

#112 [UserTokensController] Added validators.
  src/controllers/UserTokensController.ts
  src/validators/UserTokensValidators.ts
Labels: bug, controller

#113 [Logger] Added system logger.
  src/config.ts
  src/core/Logger.ts
  src/entities/SystemLog.ts
Labels: development, entity
