Repository AtlasRender/atlas-core, pull requests merged in 2020-11, with the labels that each got.

#118 Move jwt key to redis
  package.json
  src/core/Authenticator.ts
  src/core/Server.ts
  src/globals.ts
  src/index.ts
  yarn.lock
Labels: dependencies, development

#124 Fix incorrect jwt key sync
  src/controllers/LoginController.ts
  src/controllers/UsersController.ts
  src/core/Authenticator.ts
  src/core/Server.ts
  src/index.ts
Labels: bug

#125 Add version route
  src/controllers/VersionsController.ts
  src/core/Authenticator.ts
  src/index.ts
Labels: controller, development

#126 [Global] Raised app version to 1.0.1
  package.json
  src/controllers/VersionsController.ts
Labels: development, testing

#129 [RolesController] Added console logs to getRoles() function.
  src/controllers/RolesController.ts
Labels: controller, testing

#130 [Authenticator] (closes #119) Added secretLoader for koa-jwt middleware.
  src/core/Authenticator.ts
  src/core/Server.ts
Labels: bug, invalid

#141 Created task reports processor
  .idea/sqldialects.xml
  src/controllers/JobController.ts
  src/core/Logger.ts
  src/entities/RenderJob.ts
  src/entities/RenderJobLog.ts
  src/entities/RenderTask.ts
  src/entities/RenderTaskAttempt.ts
  src/entities/RenderTaskAttemptLog.ts
  src/index.ts
  src/processors/JobsProcessor.ts
  src/processors/TaskReportsProcessor.ts
  src/validators/JobRequestValidators.ts
Labels: AMQP, controller, development

#142 (#95) add roles switchers
  src/controllers/OrganizationsController.ts
  src/controllers/RolesController.ts
  src/entities/Role.ts
  src/middlewares/organizationRequestMiddlewares.ts
  src/middlewares/withRoleAccessMiddleware.ts
  src/validators/OrganizationRequestValidators.ts
Labels: controller, development

#146 [UsersController] Changed editUser() to work with full user data.
  src/controllers/UsersController.ts
Labels: controller, development

#148 [RenderTask entity] Changed jobId to be notnull.
  src/entities/RenderTask.ts
Labels: bug, high priority

#151 [Role entity] Changed organization column to be notnull.
  src/entities/Role.ts
Labels: bug

#152 [Organization entity] Changed ownerUser relation to be ManyToOne.
  src/entities/Organization.ts
Labels: bug

#150 Add plugin controller
  package.json
  src/config.ts
  src/controllers/PluginController.ts
  src/controllers/UploadController.ts
  src/core/Server.ts
  src/entities/BasicPlugin.ts
  src/entities/GlobalPlugin.ts
  src/entities/Organization.ts
  src/entities/OrganizationLog.ts
  src/entities/Plugin.ts
  src/entities/RenderJob.ts
  src/entities/RenderJobLog.ts
  src/entities/RenderTask.ts
  src/entities/RenderTaskAttempt.ts
  src/entities/RenderTaskAttemptLog.ts
  src/entities/Role.ts
  src/entities/Slave.ts
  src/entities/SystemLog.ts
  src/entities/Temp.ts
  src/entities/User.ts
  src/entities/UserToken.ts
  src/globals.ts
  src/index.ts
  src/interfaces/RestFile.ts
  src/utils/streamToBuffer.ts
  src/validators/PluginRequestValidators.ts
  yarn.lock
Labels: controller, development

#155 [Server] Changed cors settings.
  src/core/Server.ts
Labels: bug, controller, development

#156 [LoginController] Changed logic.
  src/controllers/LoginController.ts
Labels: development

#157 [CORS] Added origin and accepted headers.
  src/controllers/PluginController.ts
  src/core/Server.ts
Labels: bug

#159 [UploadController] Fixed bugs with user search in delete and deg plug…
  src/controllers/UploadController.ts
Labels: bug, controller

#160 Add restrictions to upload controller.
  src/controllers/UploadController.ts
  src/entities/Temp.ts
Labels: controller, development

#164 (#96,#106) rework organization creation
  src/controllers/OrganizationsController.ts
  src/controllers/RolesController.ts
  src/controllers/UsersController.ts
  src/validators/OrganizationRequestValidators.ts
Labels: controller, development

#165 [Role entity] (#162) Added canEditAudit column.
  .idea/webResources.xml
  package.json
  src/controllers/OrganizationsController.ts
  src/controllers/RolesController.ts
  src/entities/Role.ts
  src/validators/OrganizationRequestValidators.ts
Labels: development, enhancement

#166 [GLOBAL] (#47) Changed all ctx.throw on RequestError.
  src/controllers/OrganizationsController.ts
  src/controllers/UsersController.ts
  yarn.lock
Labels: development

#173 Add plugin settings validation
  .idea/atlas-core.iml
  .idea/modules.xml
  package.json
  src/controllers/JobController.ts
  src/controllers/PluginController.ts
  src/entities/BasicPlugin.ts
  src/entities/Plugin.ts
  src/entities/RenderJob.ts
  src/globals.ts
  src/validators/JobRequestValidators.ts
  src/validators/PluginRequestValidators.ts
  tsconfig.json
  yarn.lock
Labels: controller, dependencies, development

#175 Added progress and submitter to
  src/config.ts
  src/controllers/JobController.ts
  src/entities/RenderJob.ts
  src/entities/User.ts
  src/subscribers/RenderTaskSubscriber.ts
Labels: controller, development, subscriber

#177 Add jsdoc to entities
  src/controllers/JobController.ts
  src/entities/BasicPlugin.ts
  src/entities/Organization.ts
  src/entities/OrganizationLog.ts
  src/entities/Plugin.ts
  src/entities/RenderJob.ts
  src/entities/RenderJobLog.ts
  src/entities/RenderTask.ts
  src/entities/RenderTaskAttempt.ts
  src/entities/RenderTaskAttemptLog.ts
  src/entities/Role.ts
  src/entities/Slave.ts
  src/entities/SystemLog.ts
  src/entities/Temp.ts
  src/entities/User.ts
  src/entities/UserToken.ts
Labels: documentation, entity

#179 (#176) add personal data entity
  src/config.ts
  src/controllers/JobController.ts
  src/controllers/LoginController.ts
  src/controllers/PluginController.ts
  src/controllers/UserTokensController.ts
  src/controllers/UsersController.ts
  src/entities/Organization.ts
  src/entities/User.ts
  src/entities/UserPrivateData.ts
  src/entities/UserToken.ts
Labels: development, entity

#180 Added WebSocket server
  package.json
  src/controllers/PluginController.ts
  src/core/Authenticator.ts
  src/core/WebSocket.ts
  src/globals.ts
  src/index.ts
  src/interfaces/UserNotificationMessage.ts
  src/interfaces/WebSocketSession.ts
  src/processors/JobsProcessor.ts
  src/processors/TaskReportsProcessor.ts
  src/processors/UserNotificationProcessor.ts
  yarn.lock
Labels: dependencies, development

#183 [PluginController] Added get plugin route.
  src/controllers/PluginController.ts
Labels: controller, development

#185 Connecting monitor to core websocket
  package.json
  src/core/WebSocket.ts
  src/globals.ts
  src/subscribers/RenderTaskSubscriber.ts
  yarn.lock
Labels: development, subscriber
