Repository AtlasRender/atlas-core, pull requests merged in 2021-01, with the labels that each got.

#244 Improve error handler.
  .env.example
  .gitignore
  src/config.ts
  src/core/Server.ts
  src/interfaces/ResponseBody.ts
  src/interfaces/ServerConfig.ts
Labels: development

#246 Hotfix for tests
  .idea/runConfigurations/Test_with_Jest.xml
  jest.config.js
  package.json
  src/controllers/LoginController.test.ts
  src/entities/Temp.ts
  tests/config.ts
  tests/controllers/LoginController.test.ts
  tests/mocks/runtime.ts
  tests/mocks/teardown.ts
  tests/utils/getFramesFromRange.test.ts
  tsconfig.json
Labels: development

#248 Creating slave connection system
  src/config.ts
  src/controllers/JobController.ts
  src/controllers/LoginController.ts
  src/controllers/OrganizationsController.ts
  src/controllers/PluginController.ts
  src/controllers/RenderTaskAttemptController.ts
  src/controllers/RolesController.ts
  src/controllers/TasksController.ts
  src/controllers/UploadController.ts
  src/controllers/UserTokensController.ts
  src/controllers/UsersController.ts
  src/core/ClientWS.ts
  src/core/Logger.ts
  src/core/SlaveWS.ts
  src/core/WebSocket.ts
  src/entities/common/FrameRange.ts
  src/entities/common/FrameRangeItem.ts
  src/entities/common/FrameRangePair.ts
  src/entities/common/SlaveWSMessage.ts
  src/entities/typeorm/BasicPlugin.ts
  src/entities/typeorm/GlobalPlugin.ts
  src/entities/typeorm/Organization.ts
  src/entities/typeorm/OrganizationLog.ts
  src/entities/typeorm/Plugin.ts
  src/entities/typeorm/RenderJob.ts
  src/entities/typeorm/RenderJobLog.ts
  src/entities/typeorm/RenderTask.ts
  src/entities/typeorm/RenderTaskAttempt.ts
  src/entities/typeorm/RenderTaskAttemptLog.ts
  src/entities/typeorm/Role.ts
  src/entities/typeorm/Slave.ts
  src/entities/typeorm/SystemLog.ts
  src/entities/typeorm/Temp.ts
  src/entities/typeorm/User.ts
  src/entities/typeorm/UserPrivateData.ts
  src/entities/typeorm/UserToken.ts
  src/index.ts
  src/interfaces/JSONObject.ts
  src/interfaces/RenderJobFields.ts
  src/interfaces/RenderTaskFields.ts
  src/interfaces/SlaveWS/SlaveMessage.ts
  src/interfaces/SlaveWS/TaskReport.ts
  src/interfaces/UserWithPermissions.ts
  src/interfaces/WebSocketOptions.ts
  src/interfaces/WebSocketSession.ts
  src/middlewares/organizationRequestMiddlewares.ts
  src/middlewares/withRoleAccessMiddleware.ts
  src/processors/JobsProcessor.ts
  src/processors/TaskReportsProcessor.ts
  src/processors/UserNotificationProcessor.ts
  src/subscribers/RenderJobSubscriber.ts
  src/subscribers/RenderTaskAttemptLogSubscriber.ts
  src/subscribers/RenderTaskAttemptSubscriber.ts
  src/subscribers/RenderTaskSubscriber.ts
  src/validators/SlaveWS/SlaveResponsePayloadTaskReportSchema.ts
  src/validators/SlaveWS/SlaveResponseSchema.ts
  tests/core/FrameRange/FrameRange.test.ts
  tests/core/FrameRange/FrameRangeItem.test.ts
  tests/core/FrameRange/FrameRangePair.test.ts
Labels: controller, development, optimization, websocket

#254 Removed comments from CI
  .github/workflows/docker-image-publish.yml
Labels: development

#257 Creating config system
  src/core/SystemOptions.ts
  src/index.ts
Labels: development, optimization

#258 Creating slave connection system
  package.json
  src/core/SlaveWS.ts
  src/core/WebSocket.ts
  src/entities/typeorm/Slave.ts
  yarn.lock
Labels: development, optimization, websocket

#263 Adding config creator
  .env.development
  .env.example
  Dockerfile
  docker-compose.yaml
  kubernetes/deployment.yaml
  src/core/SystemConfig.ts
  src/core/SystemOptions.ts
  src/envDispatcher.ts
  src/index.ts
  src/interfaces/Ref.ts
  src/utils/createRef.ts
  src/utils/getProjectRoot.ts
Labels: development, optimization, security

#264 Changed organization-slave relation to OneToMany.
  src/entities/typeorm/Organization.ts
  src/entities/typeorm/Slave.ts
Labels: entity

#267 Created version incrementor
  .github/workflows/docker-image-publish.yml
  .versionrc.json
  Dockerfile
  package.json
  src/controllers/VersionsController.ts
  yarn.lock
Labels: controller, dependencies, development

#270 fix env
  kubernetes/deployment.yaml
Labels: bug

#276 fix Dockerfile file
  Dockerfile
Labels: bug

#278 Fix withRoleAccessMiddleware.
  src/controllers/OrganizationsController.ts
  src/middlewares/organizationRequestMiddlewares.ts
  src/middlewares/withRoleAccessMiddleware.ts
  src/utils/organizations/getUserPermissionLevelById.ts
Labels: bug

#280 Adding controller decorators
  .env.development
  src/controllers/JobController.ts
  src/controllers/LoginController.ts
  src/controllers/OrganizationsController.ts
  src/controllers/PluginController.ts
  src/controllers/RenderTaskAttemptController.ts
  src/controllers/RolesController.ts
  src/controllers/TasksController.ts
  src/controllers/UploadController.ts
  src/controllers/UserTokensController.ts
  src/controllers/UsersController.ts
  src/controllers/VersionsController.ts
  src/core/Controller.ts
  src/decorators/HTTPController.ts
  src/decorators/NestedController.ts
  src/decorators/Route.ts
  src/decorators/RouteMiddleware.ts
  src/decorators/RouteValidation.ts
  src/envDispatcher.ts
  src/middlewares/withRoleAccessMiddleware.ts
Labels: controller, development, optimization
